uwsgi:
  http: :7007
  wsgi-file: src/core/server.py
  master: true
  safe-pidfile: src/core/server.pid
  
      

  # products
  route: ^/store/products/create static:../browser1/srv/store/products/index.html
  route: ^/store/products/index(.*) static:../browser1/srv/store/products/index$1
  load-file-in-cache: ../browser1/srv/store/products/index.html
  route: ^/store/products/(.*) static:../browser1/srv/store/products/instance.html
  load-file-in-cache: ../browser1/srv/store/products/instance.html
      

  # customers
  route: ^/store/customers/create static:../browser1/srv/store/customers/index.html
  route: ^/store/customers/index(.*) static:../browser1/srv/store/customers/index$1
  load-file-in-cache: ../browser1/srv/store/customers/index.html
  route: ^/store/customers/(.*) static:../browser1/srv/store/customers/instance.html
  load-file-in-cache: ../browser1/srv/store/customers/instance.html
      
  
      

  # employees
  route: ^/admin/employees/create static:../browser1/srv/admin/employees/index.html
  route: ^/admin/employees/index(.*) static:../browser1/srv/admin/employees/index$1
  load-file-in-cache: ../browser1/srv/admin/employees/index.html
  route: ^/admin/employees/(.*) static:../browser1/srv/admin/employees/instance.html
  load-file-in-cache: ../browser1/srv/admin/employees/instance.html
      
  


  static-map: /=../browser1/srv/
  static-index: index.html
  static-expires: /* 0
  
  py-auto-reload: 1